[
  {
    "father":"charles","mother":"lina","child1":"theocha",
  "child2":"tisha","child3":"theo"
  },
  {
    'father':'Tsediso','mother':'Edna','child1':'Nala',
  'child2':'Junior','child3':'tsepo'
  },
  {
    father:'Justin',mother:'Loini',child1:'Helam',
  child2:'Lora',child3:'twins'
  },
  {
    'father':'Steve','mother':'Chris','child1':'Landon',
  child2:'Paco','child3':'stan','child4':'levi','child5':'curtis',child6:'josh'
  },
  {
    'father':'Natangwe','mother':'paula','child1':'Julius',
  'child2':'Nafimane','child3':'Selma','child4':'Hafeni','child5':'tangeni'
  }
]